[tool.poetry]
name = "mysneak-scraper"
version = "0.1.0"
description = ""
authors = ["bschulz <moin@bschulz.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
